### ISSUE TITLE
last change time should be fixed

### ISSUE THREAD

**Issue by bilalyasar** [Garaj/headshot#1]
I think it should show readable date rather than timestamp.

related line: https://github.com/Garaj/headshot/blob/master/parse/cloud/main.js#L52

**Comment by tasomaniac** [comment]
Space API requires it to be a timestamp. Other applications read that
value.
We can add additional human readable time.

**Comment by tasomaniac** [comment]
Anyone can add additional field if it is needed. Closing this for now.
